/// Flutter icons SamSebeTrener
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SamSebeTrener
///      fonts:
///       - asset: fonts/SamSebeTrener.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class SamSebeTrener {
  SamSebeTrener._();

  static const _kFontFam = 'SamSebeTrener';
  static const String? _kFontPkg = null;

  static const IconData profile = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData barbell = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plate = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
